pom.xml, src/main/java/it/pagopa/pn/deliverypush/middleware/queue/producer/abstractions/actionspool/impl/ActionsPoolImpl.java, src/main/java/it/pagopa/pn/deliverypush/middleware/queue/producer/abstractions/webhookspool/impl/WebhooksPoolImpl.java, src/main/java/it/pagopa/pn/deliverypush/middleware/queue/producer/action/sqs/SqsActionProducer.java, src/main/java/it/pagopa/pn/deliverypush/middleware/queue/producer/webhook/sqs/SqsWebhookProducer.java, src/test/java/it/pagopa/pn/deliverypush/middleware/queue/producer/abstractions/actionspool/impl/ActionPoolImplTest.java, src/test/java/it/pagopa/pn/deliverypush/middleware/queue/producer/abstractions/actionspool/impl/ActionsPoolImplTest.java, src/test/java/it/pagopa/pn/deliverypush/middleware/queue/producer/abstractions/webhookspool/impl/WebhooksPoolImplTest.java
Dipende dalle seguenti PR:
- https://github.com/pagopa/pn-commons/pull/78
- https://github.com/pagopa/pn-model/pull/85
=> PN-2012 pn-commons version to 0.0.2-SNAPSHOT

src/test/java/it/pagopa/pn/deliverypush/service/impl/GetLegalFactServiceImplTest.java
Eliminata classi DTO di pn-model
=> PN-2549 pulizia model

src/main/java/it/pagopa/pn/deliverypush/utils/HtmlSanitizer.java, src/test/java/it/pagopa/pn/deliverypush/utils/HtmlSanitizerTest.java
Uso dei generics nel sanitizer.
=> PN-2579 generics in HtmlSanitizer

docs/openapi/api-external-b2b-webhook-v1.yaml, docs/openapi/api-internal-b2b-webhook-v1.yaml
- aggiunta la sezione collapsible "AMBIENTI" che descrive gli ambienti
- aggiunta nella tendina "servers" l'ambiente di collaudo
- allineamento internal-external
=> Aggiornamento Swagger

src/main/java/it/pagopa/pn/deliverypush/action/notificationview/ViewNotification.java, src/main/java/it/pagopa/pn/deliverypush/action/refinement/RefinementHandler.java, src/main/java/it/pagopa/pn/deliverypush/action/startworkflow/AttachmentUtils.java, src/main/java/it/pagopa/pn/deliverypush/service/impl/TimeLineServiceImpl.java, src/test/java/it/pagopa/pn/deliverypush/action/RefinementHandlerTest.java, src/test/java/it/pagopa/pn/deliverypush/action/notificationview/ViewNotificationTest.java, src/test/java/it/pagopa/pn/deliverypush/service/impl/TimeLineServiceImplTest.java
allegati 120 giorni da perfezionamento
=> PN-2472 allegati 120 giorni da perfezionamento

src/main/java/it/pagopa/pn/deliverypush/action/startworkflow/AttachmentUtils.java
Fix chiamata safeStorage con retention
=> PN-2472 fix chiamata safeStorage con retention

src/test/java/it/pagopa/pn/deliverypush/LocalStackTestConfig.java
=> PN-2472 fix network localstack

src/main/java/it/pagopa/pn/deliverypush/action/notificationview/ViewNotification.java, src/main/java/it/pagopa/pn/deliverypush/action/refinement/RefinementHandler.java
Commentata temporaneamente chiamata a Safe Storage
=> PN-2472 commentata temporaneamente chiamata a SafeStorage

scripts/aws/cfn/microservice-dev-cfg.json, scripts/aws/cfn/microservice-svil-cfg.json, scripts/aws/cfn/microservice-uat-cfg.json, scripts/aws/cfn/microservice.yml, src/main/java/it/pagopa/pn/deliverypush/PnDeliveryPushConfigs.java, src/main/java/it/pagopa/pn/deliverypush/action/notificationview/ViewNotification.java, src/main/java/it/pagopa/pn/deliverypush/action/refinement/RefinementHandler.java, src/main/resources/application.properties, src/test/java/it/pagopa/pn/deliverypush/action/RefinementHandlerTest.java, src/test/java/it/pagopa/pn/deliverypush/action/notificationview/ViewNotificationTest.java, src/test/resources/application-test.properties
Esternalizzata conf days della retention degli allegati
=> PN-2819 Esternalizzata conf days della retention degli allegati

src/main/java/it/pagopa/pn/deliverypush/action/utils/TimelineUtils.java, src/main/java/it/pagopa/pn/deliverypush/dto/timeline/TimelineElementInternal.java, src/main/java/it/pagopa/pn/deliverypush/dto/timeline/details/PublicRegistryResponseDetailsInt.java, src/main/java/it/pagopa/pn/deliverypush/dto/timeline/details/SendAnalogFeedbackDetailsInt.java, src/main/java/it/pagopa/pn/deliverypush/dto/timeline/details/SendDigitalFeedbackDetailsInt.java, src/main/java/it/pagopa/pn/deliverypush/middleware/dao/timelinedao/dynamo/entity/TimelineElementEntity.java, src/main/java/it/pagopa/pn/deliverypush/middleware/dao/timelinedao/dynamo/mapper/DtoToEntityTimelineMapper.java, src/main/java/it/pagopa/pn/deliverypush/middleware/dao/timelinedao/dynamo/mapper/EntityToDtoTimelineMapper.java, src/test/java/it/pagopa/pn/deliverypush/action/utils/DigitalWorkFlowUtilsTest.java, src/test/java/it/pagopa/pn/deliverypush/action/utils/TimelineUtilsTest.java, src/test/java/it/pagopa/pn/deliverypush/dto/timeline/details/PublicRegistryResponseDetailsIntTest.java, src/test/java/it/pagopa/pn/deliverypush/middleware/dao/timelinedao/dynamo/mapper/DtoToEntityTimelineMapperTest.java, src/test/java/it/pagopa/pn/deliverypush/middleware/dao/timelinedao/dynamo/mapper/EntityToDtoTimelineMapperTest.java, src/test/java/it/pagopa/pn/deliverypush/middleware/timelinedao/TimelineDaoDynamoTest.java
Agggiunti campi per analisi DataLake
=> PN-2625 aggiunta campi per DataLake

scripts/aws/cfn/microservice.yml
=> PN-2898: removed comments and useless blank lines

scripts/aws/cfn/microservice.yml
=> PN-2732: added AlbSecurityGroup parameter

src/main/resources/documents_composition_templates/NotificationAARForPEC.html
changed text, style and position of the component in the file
=> refactor: change html for the pec notify

src/main/resources/documents_composition_templates/NotificationAARForPEC.html
Removes double 'una' in NotificationAARForPEC.html
=> fix: removes typo from NotificationAARForPEC.html

src/main/resources/documents_composition_templates/NotificationViewedLegalFact.html
Removes 'in quanto irrilevante ai fini del perfezionamento della notificazione' from NotificationViewedLegalFact.html
=> fix: change copy in NotificationViewedLegalFact

src/main/java/it/pagopa/pn/deliverypush/action/startworkflow/ReceivedLegalFactCreationResponseHandler.java, src/test/java/it/pagopa/pn/deliverypush/action/startworkflow/ReceivedLegalFactCreationResponseHandlerTest.java
Ripristino safestorage originale
=> Ripristino safestorage

docs/openapi/api-external-b2b-webhook-bundle.yaml, docs/openapi/api-external-b2b-webhook.yaml, docs/openapi/api-internal-b2b-webhook.yaml
- rimosso PAID dalla lista dei filterValues
=> aggiornamento-swagger

docs/openapi/api-external-b2b-webhook-bundle.yaml, docs/openapi/schemas-pn-timeline.yaml
Corretto nome dell'evento VALIDATE_NORMALIZE_ADDRESSES_REQUEST
=> Aggiornamento - swagger

pom.xml, src/main/resources/documents_composition_templates/NotificationAARForEMAIL.html
=> fix style on email

src/main/resources/documents_composition_templates/NotificationAAR.html, src/main/resources/documents_composition_templates/NotificationAARForEMAIL.html, src/main/resources/documents_composition_templates/NotificationAARForPEC.html, src/test/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactPdfGeneratorTest.java
Fixed AAR layout and email/pec copies
=> fix(Pn-7877): aar non consistente

package-lock.json, src/main/resources/documents_composition_templates/NotificationAARForEMAIL.html
Refactoring of NotificationAARForEMAIL template in /src/main/resources/documents_composition_templates/NotificationAARForEMAIL.html file.
=> feat(PN-7708): refactoring NotificationAARForEMAIL.html template

package-lock.json, src/main/resources/documents_composition_templates/NotificationAARForEMAIL.html, src/main/resources/documents_composition_templates/NotificationAARForPEC.html
Refactoring of NotificationAARForPEC template in /src/main/resources/documents_composition_templates/NotificationAARForPEC.html file.
=> feat(PN-7709): refactoring NotificationAARForPEC.html template

src/main/resources/documents_composition_templates/NotificationAAR.html
Updated copy in NotificationAAR.html
=> Fix(PN-8573): updated copy in NotificationAAR.html

pom.xml, src/main/resources/documents_composition_templates/NotificationAAR_RADDalt.html, src/test/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactPdfGeneratorTest.java
Updated AAR copy for RADD alternative with second version proposed
=> fix: copy AAR_RADDalt template

src/main/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactGenerator.java, src/main/resources/documents_composition_templates/PecDeliveryWorkflowLegalFact.html, src/test/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactPdfGeneratorTest.java, src/test/java/it/pagopa/pn/deliverypush/utils/HtmlSanitizerTest.java
- add digital domicile condition in pecdeliveryworkflow template
- add realative tests
- add variable type in PecDeliveryInfo
=> feat(PN-12522): update PecDeliveryWorkflow template

src/main/java/it/pagopa/pn/deliverypush/dto/ext/delivery/notification/NotificationInt.java, src/main/java/it/pagopa/pn/deliverypush/legalfacts/DocumentComposition.java, src/main/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactGenerator.java, src/main/java/it/pagopa/pn/deliverypush/service/impl/SaveLegalFactsServiceImpl.java, src/test/java/it/pagopa/pn/deliverypush/action/it/utils/TestUtils.java, src/test/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactPdfGeneratorTest.java, src/test/java/it/pagopa/pn/deliverypush/service/impl/SaveLegalFactsServiceImplTest.java
[PN-12928] - New method to generate notification cancelled legalFact with different languages
[PN-12928]: https://pagopa.atlassian.net/browse/PN-12928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-12928] - New method to generate notification cancelled legalFact with different languages

functions/versioningV1V2Webhook/src/app/handlers/baseHandler.js, functions/versioningV1V2Webhook/src/app/handlers/consumeEventStreamHandler.js, functions/versioningV1V2Webhook/src/app/handlers/createEventStreamHandler.js, functions/versioningV1V2Webhook/src/app/handlers/disableEventStreamHandler.js, functions/versioningV1V2Webhook/src/app/handlers/getEventStreamHandler.js, functions/versioningV1V2Webhook/src/app/handlers/mapper/transformProgressResponseFromV25ToV24.js, functions/versioningV1V2Webhook/src/app/handlers/updateEventStreamHandler.js, functions/versioningV1V2Webhook/src/test/handlers/consumeEventStreamHandler.test.js, functions/versioningV1V2Webhook/src/test/handlers/createEventStreamHandler.test.js, functions/versioningV1V2Webhook/src/test/handlers/disableEventStreamHandler.test.js, functions/versioningV1V2Webhook/src/test/handlers/getEventStreamHandler.test.js, functions/versioningV1V2Webhook/src/test/handlers/mapper/progressResponseV25.json, functions/versioningV1V2Webhook/src/test/handlers/mapper/transformProgressResponseV25V24.test.js, functions/versioningV1V2Webhook/src/test/handlers/updateEventStreamHandler.test.js, scripts/aws/cfn/microservice.yml, src/main/resources/application.properties
[PN-12952] - Modified lambda versioningV1V2Webhook to accept new version 2.5
[PN-12952]: https://pagopa.atlassian.net/browse/PN-12952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-12952] - Modified lambda versioningV1V2Webhook to accept new version 2.5

functions/versioningGetNotificationLegalFactsLambda/index.js, functions/versioningGetNotificationLegalFactsLambda/package-lock.json, functions/versioningGetNotificationLegalFactsLambda/package.json, functions/versioningGetNotificationLegalFactsLambda/sonar-project.properties, functions/versioningGetNotificationLegalFactsLambda/sonarqube-scanner.js, functions/versioningGetNotificationLegalFactsLambda/src/app/eventHandler.js, functions/versioningGetNotificationLegalFactsLambda/src/app/mapper/mapperV20ToV1.js, functions/versioningGetNotificationLegalFactsLambda/src/test/eventHandler.test.js, functions/versioningGetNotificationLegalFactsLambda/src/test/response.json, scripts/aws/cfn/microservice-dev-cfg.json, scripts/aws/cfn/microservice.yml, scripts/aws/cfn/storage.yml
[PN-12951] - New lambda versioningGetNotificationLegalFactsLambda
[PN-12951]: https://pagopa.atlassian.net/browse/PN-12951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-12951] - New lambda versioningGetNotificationLegalFactsLambda

src/main/java/it/pagopa/pn/deliverypush/service/impl/SchedulerServiceImpl.java, src/test/java/it/pagopa/pn/deliverypush/service/impl/SchedulerServiceImplTest.java
[PN-12922] - Added condition on NOTIFICATION_CANCELLED
[PN-12922]: https://pagopa.atlassian.net/browse/PN-12922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-12922] - Added condition on NOTIFICATION_CANCELLED

functions/versioningGetNotificationLegalFactsLambda/src/app/eventHandler.js, functions/versioningGetNotificationLegalFactsLambda/src/test/eventHandler.test.js
[PN-12922] - Removed check on event.resource
[PN-12922]: https://pagopa.atlassian.net/browse/PN-12922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-12922] - Removed check on event.resource

src/main/java/it/pagopa/pn/deliverypush/action/utils/TimelineUtils.java, src/main/java/it/pagopa/pn/deliverypush/rest/PnLegalFactsController.java
PN-12922 Aggiunto controllo sulla disponibilità degli atti opponibili a terzi
=> PN-12922 Aggiunto controllo sulla disponibilità degli atti opponibili a terzi

src/test/java/it/pagopa/pn/deliverypush/action/utils/TimelineUtilsTest.java, src/test/java/it/pagopa/pn/deliverypush/rest/PnLegalFactsControllerTest.java
[PN-12922] - Added Junit tests
[PN-12922]: https://pagopa.atlassian.net/browse/PN-12922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-12922] - Added Junit tests

functions/versioningV1V2Webhook/src/app/handlers/updateEventStreamHandler.js
[PN-13288] - Fix update requestBody v23
[PN-13288]: https://pagopa.atlassian.net/browse/PN-13288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-13288] - Fix update requestBody v23

src/main/resources/documents_composition_templates/AnalogDeliveryWorkflowFailureLegalFact.html, src/main/resources/documents_composition_templates/AnalogDeliveryWorkflowFailureLegalFact_de.html, src/main/resources/documents_composition_templates/AnalogDeliveryWorkflowFailureLegalFact_fr.html, src/main/resources/documents_composition_templates/AnalogDeliveryWorkflowFailureLegalFact_sl.html, src/main/resources/documents_composition_templates/NotificationAAR_RADDalt_de.html, src/main/resources/documents_composition_templates/NotificationAAR_RADDalt_fr.html, src/main/resources/documents_composition_templates/NotificationAAR_RADDalt_sl.html, src/main/resources/documents_composition_templates/NotificationAAR_de.html, src/main/resources/documents_composition_templates/NotificationAAR_fr.html, src/main/resources/documents_composition_templates/NotificationAAR_sl.html, src/main/resources/documents_composition_templates/NotificationCancelledLegalFact.html, src/main/resources/documents_composition_templates/NotificationCancelledLegalFact_de.html, src/main/resources/documents_composition_templates/NotificationCancelledLegalFact_fr.html, src/main/resources/documents_composition_templates/NotificationCancelledLegalFact_sl.html, src/main/resources/documents_composition_templates/NotificationReceivedLegalFact.html, src/main/resources/documents_composition_templates/NotificationReceivedLegalFact_de.html, src/main/resources/documents_composition_templates/NotificationReceivedLegalFact_fr.html, src/main/resources/documents_composition_templates/NotificationReceivedLegalFact_sl.html, src/main/resources/documents_composition_templates/NotificationViewedLegalFact.html, src/main/resources/documents_composition_templates/NotificationViewedLegalFact_de.html, src/main/resources/documents_composition_templates/NotificationViewedLegalFact_fr.html, src/main/resources/documents_composition_templates/NotificationViewedLegalFact_sl.html, src/main/resources/documents_composition_templates/PecDeliveryWorkflowLegalFact.html, src/main/resources/documents_composition_templates/PecDeliveryWorkflowLegalFact_de.html, src/main/resources/documents_composition_templates/PecDeliveryWorkflowLegalFact_fr.html, src/main/resources/documents_composition_templates/PecDeliveryWorkflowLegalFact_sl.html
Remove `<span>` in tag `<title>` to fix title in tab browser
=> fix PN-13357: title in browser tab

src/main/resources/documents_composition_templates/NotificationAAR.html, src/main/resources/documents_composition_templates/NotificationAAR_RADDalt.html
figma for AAR e AAR RADD_alt https://www.figma.com/design/Wp9Rjhi1NO8Wqs6n6qiv6l/AAR?node-id=1-130
=> fix/PN-13384: fix AAR and AAR RADDalt spaces

config/application.properties, scripts/aws/cfn/microservice-dev-cfg.json, scripts/aws/cfn/microservice.yml, src/main/java/it/pagopa/pn/deliverypush/config/PnDeliveryPushConfigs.java
[PN-13365] - New flag FeatureUnreachableRefinementPostAARStartDate
[PN-13365]: https://pagopa.atlassian.net/browse/PN-13365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-13365] - New flag FeatureUnreachableRefinementPostAARStartDate

src/main/java/it/pagopa/pn/deliverypush/action/completionworkflow/AnalogFailureDeliveryCreationResponseHandler.java, src/test/java/it/pagopa/pn/deliverypush/action/completionworkflow/AnalogFailureDeliveryCreationResponseHandlerTest.java, src/test/java/it/pagopa/pn/deliverypush/action/it/CommonTestConfiguration.java
[PN-13366] - Changed schedule refinement date and added if condition on it
[PN-13366]: https://pagopa.atlassian.net/browse/PN-13366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-13366] - Changed schedule refinement date and added if condition on it

src/main/java/it/pagopa/pn/deliverypush/service/impl/TimeLineServiceImpl.java, src/main/java/it/pagopa/pn/deliverypush/service/mapper/SmartMapper.java, src/main/java/it/pagopa/pn/deliverypush/service/mapper/TimelineMapper.java, src/main/java/it/pagopa/pn/deliverypush/service/mapper/TimelineMapperAfterFix.java, src/main/java/it/pagopa/pn/deliverypush/service/mapper/TimelineMapperBeforeFix.java, src/main/java/it/pagopa/pn/deliverypush/service/mapper/TimelineMapperFactory.java, src/main/java/it/pagopa/pn/deliverypush/service/utils/WebhookUtils.java, src/main/java/it/pagopa/pn/deliverypush/utils/StatusUtils.java, src/test/java/it/pagopa/pn/deliverypush/action/it/CommonTestConfiguration.java, src/test/java/it/pagopa/pn/deliverypush/service/impl/TimeLineServiceImplTest.java, src/test/java/it/pagopa/pn/deliverypush/service/mapper/SmartMapperTest.java, src/test/java/it/pagopa/pn/deliverypush/service/utils/WebhookUtilsTest.java, src/test/java/it/pagopa/pn/deliverypush/utils/StatusUtilsMultiRecipientTest.java, src/test/java/it/pagopa/pn/deliverypush/utils/StatusUtilsTest.java
[PN-13367] - Refactor mapping timeline element
[PN-13367]: https://pagopa.atlassian.net/browse/PN-13367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-13367] - Refactor mapping timeline element

src/main/java/it/pagopa/pn/deliverypush/action/digitalworkflow/DigitalWorkFlowExternalChannelResponseHandler.java, src/main/java/it/pagopa/pn/deliverypush/action/digitalworkflow/DigitalWorkFlowHandler.java, src/main/java/it/pagopa/pn/deliverypush/action/digitalworkflow/SendDigitalFinalStatusResponseHandler.java, src/test/java/it/pagopa/pn/deliverypush/action/digitalworkflow/SendDigitalFinalStatusResponseHandlerTest.java
[PN-13625] - Modified dates for schedule refinement during the retry cycle
[PN-13625]: https://pagopa.atlassian.net/browse/PN-13625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-13625] - Modified dates for schedule refinement during the retry cycle

src/main/java/it/pagopa/pn/deliverypush/action/completionworkflow/RefinementScheduler.java, src/test/java/it/pagopa/pn/deliverypush/action/completionworkflow/RefinementSchedulerTest.java
[PN-13624] - Modified schedule digital refinement after 9pm (AAR case)
[PN-13624]: https://pagopa.atlassian.net/browse/PN-13624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-13624] - Modified schedule digital refinement after 9pm (AAR case)

scripts/aws/cfn/microservice-dev-cfg.json
[PN-13621] - new date for FeatureUnreachableRefinementPostAARStartDate
[PN-13621]: https://pagopa.atlassian.net/browse/PN-13621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-13621] - new date for FeatureUnreachableRefinementPostAARStartDate

scripts/aws/cfn/microservice-dev-cfg.json
Revert "[PN-13621] - new date for FeatureUnreachableRefinementPostAARStartDate"
[PN-13621]: https://pagopa.atlassian.net/browse/PN-13621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "[PN-13621] - new date for FeatureUnreachableRefinementPostAARStartDate"

config/application.properties, scripts/aws/cfn/application-dev.env, scripts/aws/cfn/microservice.yml, src/main/java/it/pagopa/pn/deliverypush/config/LegalFactGeneratorConfig.java, src/main/java/it/pagopa/pn/deliverypush/config/PnDeliveryPushConfigs.java, src/main/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactGeneratorTemplates.java, src/main/java/it/pagopa/pn/deliverypush/middleware/externalclient/pnclient/templatesengine/TemplatesClientPec.java, src/main/java/it/pagopa/pn/deliverypush/middleware/externalclient/pnclient/templatesengine/TemplatesClientPecImpl.java, src/main/java/it/pagopa/pn/deliverypush/service/impl/ExternalChannelServiceImpl.java, src/main/java/it/pagopa/pn/deliverypush/utils/FeatureEnabledUtils.java, src/main/resources/application.properties, src/test/java/it/pagopa/pn/deliverypush/action/it/AbstractWorkflowTestConfiguration.java, src/test/java/it/pagopa/pn/deliverypush/action/it/CommonTestConfiguration.java, src/test/java/it/pagopa/pn/deliverypush/action/it/mockbean/TemplatesClientMockPec.java, src/test/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactGeneratorTemplatesTest.java, src/test/java/it/pagopa/pn/deliverypush/service/impl/ExternalChannelServiceImplAttachmentTest.java, src/test/java/it/pagopa/pn/deliverypush/service/impl/ExternalChannelServiceImplTest.java, src/test/resources/application-test.properties, src/test/resources/application-testIT.properties
* PN-14533: refactored sendDigitalNotification to implement AAR only scenario
* PN-14542: add featureFlag to override pec and add endpoint parameter for templates with actual path as default
* PN-14542: add properties to application-test.properties
* PN-14542: modified property name
* PN-14542: modified LegalFactGeneratorTemplates
* PN-14542: fix test and refactor
* PN-14542: fix test and refactor
* PN-14542: fix test and refactor
* PN-14542: change name params
* PN-14542: remove duplicated containerEnvEntry PN_DELIVERYPUSH_EMDINTEGRATIONBASEURL
* PN-14542: remove params from cfg
* PN-14542: set PN_DELIVERY_PUSH_AARONLYPECFORRADDANDPF to true
* PN-14542: set PN_DELIVERY_PUSH_AARONLYPECFORRADDANDPF to true
* PN-14542: remove cfg and clean code
* PN-14542:
* PN-14542: add default to …
=> Feature/pn 14542 (#1255)
